services:
  salvatore-viscuso-dot-dev:
    build: .
    container_name: salvatore-viscuso-dot-dev
    restart: unless-stopped
    ports:
      - "3100:80"
    env_file:
      - path: .env
        required: false
